name: laden-site
services:
  web:
    image: nginx:1.27-alpine
    restart: unless-stopped
    ports:
      - "127.0.0.1:18083:80"
    volumes:
      - laden_site:/usr/share/nginx/html:ro
      - /opt/laden-docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    read_only: true
    tmpfs:
      - /var/cache/nginx
      - /var/run
      - /tmp
    security_opt:
      - no-new-privileges:true
volumes:
  laden_site:
    external: true
    name: laden_site
