server {
    listen 80;
    server_name _;
    absolute_redirect off;
    port_in_redirect off;
    root /usr/share/nginx/html;
    index index.html;

    location = /docker/laden {
        return 301 /docker/laden/;
    }

    location = /docker/laden/ {
        return 301 /docker/laden/en/;
    }

    location /docker/laden/ {
        try_files $uri $uri/ $uri/index.html =404;
    }

    location / {
        return 404;
    }
}
