server {
    listen 80;
    server_name _;
    absolute_redirect off;
    port_in_redirect off;
    root /usr/share/nginx/html;
    index index.html;

    location = /docker/skarverakk {
        return 301 /docker/skarverakk/;
    }

    location /docker/skarverakk/ {
        try_files $uri $uri/ /docker/skarverakk/index.html;
    }

    location / {
        return 404;
    }
}
